### ISSUE TITLE
Cannot import in python nightly build

### ISSUE THREAD

**Issue by Nzbuu** [Simplistix/testfixtures#32]
On Travis, when I build with Python nightly (Python 3.6.0a0), then I get the following exception when importing. Works fine in Python 3.5.

```
__________________ ERROR collecting tests/test_controller.py ___________________
tests/test_controller.py:5: in <module>
    import testfixtures
../../../virtualenv/python3.6-dev/lib/python3.6/site-packages/testfixtures/__init__.py:21: in <module>
    from testfixtures.logcapture import LogCapture, log_capture
../../../virtualenv/python3.6-dev/lib/python3.6/site-packages/testfixtures/logcapture.py:10: in <module>
    from testfixtures.utils import wrap
../../../virtualenv/python3.6-dev/lib/python3.6/site-packages/testfixtures/utils.py:5: in <module>
    from inspect import getargspec
E   ImportError: cannot import name 'getargspec'
====================== 75 passed, 1 error in 1.24 seconds ======================
```

**Comment by Nzbuu** [comment]
I've created a PR to add Travis builds on Python nightly: https://github.com/Simplistix/testfixtures/pull/33. Let me know if you want me to update it with "allow_failures".

**Comment by cjw296** [comment]
See my comment on the pull request. FWIW, this issue appears to be a perfect case in point of why I have little interest in tracking nightlies. It looks like getargspec is back:

https://bugs.python.org/issue25486

I'm not sure why it would ever have been removed.
